name: Setup project
description: Group of actions used to setup react project
runs:
  using: composite
  steps:
    - name: Download project dependencies
      shell: bash
      run: |
        npm test