name: Release CI
run-name: Deploy version ${{ github.ref_name }}
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

# cancel workflow when there is already one launched
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Test project
        uses: ./.github/actions/test-project
  build_docker:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish
        uses: ./.github/actions/build-and-publish
        with:
          ghcr_user: ${{secrets.GHCR_USER}}
          ghcr_password: ${{secrets.GHCR_TOKEN}}
          version: ${{  github.ref_name }}
          image_name: ghcr.io/lucasmrcr/projet-web
  build_and_deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Build
        run: |
          npm run build
          tar -czvf projet-web-${{ github.ref_name }}.tar.gz build
      - name: Setup remote server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            mkdir -p ~/projet-web
      - name: Copy docker compose to remote server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: projet-web-${{ github.ref_name }}.tar.gz
          target: ~/projet-web