name: Release CI
run-name: Deploy version ${{ github.ref_name }}
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

# cancel workflow when there is already one launched
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Test project
        uses: ./.github/actions/test-project
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{secrets.GHCR_USER}}
          password: ${{secrets.GHCR_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/lucasmrcr/projet-web:${{  github.ref_name }}
            ghcr.io/lucasmrcr/projet-web:latest